### ISSUE TITLE
Support of UICollectionViewDiffableDataSource?

### ISSUE THREAD

**Issue by borgeser** [denisPoifol/CollectionModel#1]
Hi Denis,

I'm looking forward using your pod, I wonder if a support for UICollectionViewDiffableDataSource is ready? Planned?

Thanks.

**Comment by denisPoifol** [comment]
👋🏿 Can you add some more detail about what usage you would like to have with CollectionModel and UICollectionViewDiffableDataSource?
To be honest I did not used UICollectionViewDiffableDataSource that much since it requires a 13+ version of iOS.
For now CollectionModel works hand in hand with DifferenceKit to animate changes, that way it provides the same features as UICollectionViewDiffableDataSource (and more) without the requirement on the iOS version.
If there is a specific usage of UICollectionViewDiffableDataSource that is not covered by the alternative, I would gladly look into it.

**Comment by borgeser** [comment]
Nevermind, `UICollectionViewDiffableDataSource` is horrible. I don't want to use it anymore 🙃
