### ISSUE TITLE
Why are header and footer distinguished from supplementaryViewModels in CollectionViewSectionViewModel?

### ISSUE THREAD

**Issue by borgeser** [denisPoifol/CollectionModel#2]
```
public init(id: String = "",
                supplementaryViewModels: [SupplementaryViewSectionKey: SupplementaryViewModel] = [:],
                header: SupplementaryViewModel? = nil,
                footer: SupplementaryViewModel? = nil,
                cells: [CellViewModel]) {
        self.id = id
        self.header = header
        self.footer = footer
        self.supplementaryViewModels = supplementaryViewModels
        self.cells = cells
}
```

This is the initializer of `CollectionViewSectionViewModel`. We can see that `header` and `footer` are first citizen, separated from `supplementaryViewModels`.

However, this distinction is strange because there is only one method in `UICollectionViewDataSource`:
```
func collectionView(_ collectionView: UICollectionView,
        viewForSupplementaryElementOfKind kind: String,
        at indexPath: IndexPath) -> UICollectionReusableView
```

and in `UICollectionViewCell`:
```
open func register(_ viewClass: AnyClass?, forSupplementaryViewOfKind elementKind: String, withReuseIdentifier identifier: String)

open func register(_ nib: UINib?, forSupplementaryViewOfKind kind: String, withReuseIdentifier identifier: String)
```

The notions of `header` and `footer` are just specific kinds:
```
extension UICollectionView {
    @available(iOS 6.0, *)
    public class let elementKindSectionHeader: String

    @available(iOS 6.0, *)
    public class let elementKindSectionFooter: String
```

So my proposal is to remove the fields `header` and `footer`. They can still be included in `supplementaryViewModels`.
We can add syntaxic sugar if needed:
```
var header: SupplementaryViewModel? {
     return supplementaryViewModels[UICollectionView.elementKindSectionHeader]
}
```

This will also solve an issue for me.
Because with the current implementation, the function `func supplementaryViewModel(for key: SupplementaryViewKey) -> SupplementaryViewModel?` returns nil when we try to get the header or the footer.

Tell me if you agree @denisPoifol. If it's OK for you I'll submit a PR.

**Comment by denisPoifol** [comment]
In the model header and footer are kept appart from the rest of supplementary views.

SupplementaryViews are added by the `UICollectionViewLayout`, most of the time in iOS we tend to use the `UICollectionViewFlowLayout` which provides supplementary views that are headers and footers. The constraint is that headers and footers can each appear once per section. For this reason it feels reasonable to give them first class citizenship.
You could create a custom `UICollectionViewLayout` that provides multiple headers and footers per section but this feels off (to me at least).

The other issue is that to provide headers and footers using the `SupplementaryViewKey` means that we know to which `(IndexPath, String)` where the string is the kind of supplementaryView. We do know the kind for headers and footers, but the `IndexPath` is given by the `UICollectionViewLayout`, in most case it is the `UICollectionViewFlowLayout`. Which means to create a `CollectionViewModel` that works properly you would have to know at which index paths the `UICollectionViewFlowLayout` generates the headers and footers.

We could nonetheless store headers and footers in the supplementary views and hide internally how the indexPath is generated for their keys and provide easy access via the `header` and `footer` properties of the `CollectionViewModel.Section` but here again, I do not feel confortable relying on how I think `UICollectionViewFlowLayout` generates his header and footer supplementary views.

>This will also solve an issue for me.
Because with the current implementation, the function func supplementaryViewModel(for key: SupplementaryViewKey) -> SupplementaryViewModel? returns nil when we try to get the header or the footer.

I am guessing the issue is that you are implementing :
```
func collectionView(_ collectionView: UICollectionView,
        viewForSupplementaryElementOfKind kind: String,
        at indexPath: IndexPath) -> UICollectionReusableView {
        let key = SupplementaryViewKey(indexPath: indexPath, kind: kind)
        guard let supplementaryViewModel = viewModel.supplementaryViewModel(for: key) else { 
                fatalError()
        }
        let supplementaryView = collectionView.dequeueSupplementaryView(at: indexPath)
        supplementaryView.configure(with: supplementaryViewModel)
        return supplementaryView
}
```
I would suggest catching the cases were the kind is `elementKindSectionHeader` or `elementKindSectionFooter` and handling them in a separate function :
```
func header(for collectionView: UICollectionView, at section: Int) -> UICollectionReusableView {
       let supplementaryView = collectionView.dequeueSupplementaryView(at: indexPath)
        supplementaryView.configure(with: viewModel.headers[section])
        return supplementaryView
}

func footer(for collectionView: UICollectionView, at section: Int) -> UICollectionReusableView {
       let supplementaryView = collectionView.dequeueSupplementaryView(at: indexPath)
        supplementaryView.configure(with: viewModel.footers[section])
        return supplementaryView
}

func collectionView(_ collectionView: UICollectionView,
        viewForSupplementaryElementOfKind kind: String,
        at indexPath: IndexPath) -> UICollectionReusableView {
        guard  case kind != UICollectionView.elementKindSectionHeader else { 
               return header(for: collectionView, at: indexPath.section)
        }
        guard  case kind != UICollectionView.elementKindSectionFooter else { 
               return footer(for: collectionView, at: indexPath.section)
        }
        let key = SupplementaryViewKey(indexPath: indexPath, kind: kind)
        guard let supplementaryViewModel = viewModel.supplementaryViewModel(for: key) else { 
                fatalError()
        }
        let supplementaryView = collectionView.dequeueSupplementaryView(at: indexPath)
        supplementaryView.configure(with: supplementaryViewModel)
        return supplementaryView
}
```

**Comment by borgeser** [comment]
OK if I understand well, your main concern is that a `SupplementaryViewModel` is described by a `kind` and an `indexPath` (`row` + `section`). But a `header/footer` is described by a `kind`, a `section` (but no `row` here since we can only have a single header and footer by section). So we don't have a bijection.

Fair enough. To be honest, the same problem is present in the Apple API.
For instance the method
```
func collectionView(_ collectionView: UICollectionView,
                    viewForSupplementaryElementOfKind kind: String,
                    at indexPath: IndexPath) -> UICollectionReusableView
```
is also called for header and footer. So we have an `indexPath`, hurray! But it's garbage -> even for a footer, the `row` of the `indexPath` is always 0. We can't blame them, they tried to mix incompatible APIs.

I think we could do the same -> create an `indexPath` with always `row` 0 for header and footer. But I understand this is a questionable move.

Maybe you could add an utility function to mirror the `viewModel.supplementaryViewModel(for: key)` ? Like this one for instance
```
public func headerOrFooterViewModel(forKind kind: String, inSection section: Int) -> SupplementaryViewModel? {
        guard sections.count > section else { return nil }
        let section = sections[section]
        switch kind {
        case UICollectionView.elementKindSectionHeader:
            return section.header
        case UICollectionView.elementKindSectionFooter:
            return section.footer
        default:
            return nil
        }
    }
```

Have a nice evening.

**Comment by denisPoifol** [comment]
It still feels a little off to me, but I can see the use case so I added the function you suggested to the ongoing evolution branch.
Hopefully I will have time to create a new version this week.
Thanks a lot for your time.
